# Build stage for Go
FROM golang:1.20.5-bullseye as go-build
WORKDIR /app
COPY go.mod go.sum ./
RUN mount=type=cache,target=/go/pkg/mod \
    go mod download

COPY . .
RUN go build -o virtual-cluster cmd/virtual-cluster/main.go

# Final stage
FROM ubuntu:22.04
RUN mount=type=cache,target=/var/cache/apt \
    apt-get update
WORKDIR /app
COPY --from=go-build /app/virtual-cluster /app/build/virtual-cluster

